// Which boards cannot be won as often as their difficulty promises, and by
// how much.
//
// Most boards carry a mine count calibrated so that playing well wins about as
// often as it does on the classic board (`scripts/difficulty/`). A few cannot,
// and they fail in two different ways, which is why this is graded rather than
// a single flag:
//
//   * **blocked** — the board is not a puzzle. Every cell of the triakis
//     tilings has an indistinguishable twin (the same closed neighbourhood),
//     so no number can ever separate a pair and the win rate is a coin flip
//     per mine at any density: measured, 0.000 at every difficulty. There is
//     nothing to warn about, because there is nothing to play.
//   * **warn** — the board is a puzzle, but a materially harder one than its
//     difficulty promises. Rhombille and its wrapped forms end with a pocket
//     of hidden cells at exactly even odds.
//
// A board that merely missed the calibration's tolerance is not listed at all.
// A board a few points under target is a board, and marking it would say "you
// were robbed" about an ordinary loss.
//
// `data/difficulty.json` is that list, generated by the calibration and shared
// with the pygame build. Three things read it: the menu, which marks or
// disables the row; the board caption, which is the only place a randomly
// dealt board can say so; and the random launchers, which never deal a blocked
// board and deal a warned one less often.

import raw from "@data/difficulty.json";

export type Fairness = "ok" | "warn" | "blocked";

interface UnfairRow {
  level: Exclude<Fairness, "ok">;
  winRate: number;
  target: number;
  indistinguishable: number;
  cells: number;
  reason: string;
}

const UNFAIR = (raw as { unfair?: Record<string, Record<string, UnfairRow>> })
  .unfair ?? {};

/** How much less often a warned board is dealt by the random launchers. */
export const WARNED_RANDOM_WEIGHT = 0.25;

/** The row for one board, or `undefined` if it plays as its difficulty says.
 *
 * `Object.hasOwn`, never `in`: the mode comes from a share link or a menu
 * table, and `in` answers true for `toString`. Same rule as `link.ts`. */
export function unfairRow(mode: string, difficulty: string): UnfairRow | undefined {
  if (!Object.hasOwn(UNFAIR, mode)) return undefined;
  const rows = UNFAIR[mode];
  if (rows === undefined || !Object.hasOwn(rows, difficulty)) return undefined;
  return rows[difficulty];
}

/** How this board plays at this difficulty. */
export function fairnessOf(mode: string, difficulty: string): Fairness {
  return unfairRow(mode, difficulty)?.level ?? "ok";
}

/** The worst grade any difficulty of this board carries.
 *
 * The menu marks the *row*, and the difficulty pills live at the foot of the
 * page — by the time one is chosen the board is already picked, so the mark
 * has to mean something before that. */
export function modeFairness(mode: string): Fairness {
  if (!Object.hasOwn(UNFAIR, mode)) return "ok";
  const rows = Object.values(UNFAIR[mode] ?? {});
  return rows.some((r) => r.level === "blocked") ? "blocked" : "warn";
}

/** Every mode with at least one blocked difficulty. */
export function blockedModes(): string[] {
  return Object.keys(UNFAIR).filter((mode) => modeFairness(mode) === "blocked");
}

/** The line shown against a graded board. About the cause, not the number:
 * "43% instead of 96%" reads as a bug report, while what a player can act on
 * is knowing the tiling is against them. */
export function fairnessHint(level: Fairness): string | undefined {
  if (level === "blocked") {
    return "Not playable — every cell of this tiling has a look-alike twin, "
      + "so the mines can never be located, only guessed at";
  }
  if (level === "warn") {
    return "Harder than it looks — this tiling's endgames can leave a guess "
      + "no amount of care avoids";
  }
  return undefined;
}

/** The full explanation, for the page shown instead of a blocked board. */
export function blockedExplanation(mode: string, difficulty: string): string {
  const row = unfairRow(mode, difficulty);
  const twins = row?.indistinguishable ?? 0;
  const cells = row?.cells ?? 0;
  const share = cells > 0 ? ` (${twins} of its ${cells} cells)` : "";
  return (
    `This tiling puts every cell in a look-alike pair${share}: the two share `
    + "exactly the same neighbours, so no number anywhere on the board can "
    + "ever tell them apart. When a mine lands alone in a pair the only way "
    + "to finish is to toss a coin, and with one toss per mine the board is "
    + "lost long before it is solved — measured, it is won under one time in "
    + "a hundred. It is kept here because the tiling is worth looking at, but "
    + "it is not a puzzle, so it does not deal."
  );
}

/** Pick from `pool` at random. Blocked boards are never dealt; warned ones are
 * dealt a quarter as often as an ordinary board.
 *
 * `random` is injectable so the unit tests can pin the weighting instead of
 * sampling it. */
export function pickWeighted(
  pool: string[],
  random: () => number = Math.random,
): string | undefined {
  const playable = pool.filter((mode) => modeFairness(mode) !== "blocked");
  if (playable.length === 0) return undefined;
  const weights = playable.map((mode) =>
    modeFairness(mode) === "warn" ? WARNED_RANDOM_WEIGHT : 1,
  );
  const total = weights.reduce((a, b) => a + b, 0);
  let ticket = random() * total;
  for (let i = 0; i < playable.length; i++) {
    ticket -= weights[i] ?? 1;
    if (ticket < 0) return playable[i];
  }
  return playable[playable.length - 1];
}
