// Which boards cannot be won as often as their difficulty promises, and by
// how much.
//
// Most boards carry a mine count calibrated so that playing well wins about as
// often as it does on the classic board (`scripts/difficulty/`). A few cannot:
// their tiling forces coin flips the player has no way to avoid. The triakis
// boards are the extreme -- every cell there has an indistinguishable twin, so
// no number can ever separate the pair and the win rate is 0.5 per mine
// however sparse the board -- and a handful of others (rhombille and its
// wrapped forms) end with a pocket of hidden cells at exactly even odds.
//
// `data/difficulty.json` is that list, generated by the calibration and shared
// with the pygame build. Two things read it: the menu, which marks such a row
// so a player picking one knows what they are choosing, and the random
// launchers, which deal them less often than an ordinary board rather than
// hiding them.

import raw from "@data/difficulty.json";

interface UnfairRow {
  winRate: number;
  target: number;
  reason: string;
}

const UNFAIR = (raw as { unfair?: Record<string, Record<string, UnfairRow>> })
  .unfair ?? {};

/** How much less often a flagged board is dealt by the random launchers. */
export const UNFAIR_RANDOM_WEIGHT = 0.25;

/** The row for one board, or `undefined` if it calibrates normally.
 *
 * `Object.hasOwn`, never `in`: the mode comes from a share link or a menu
 * table, and `in` answers true for `toString`. Same rule as `link.ts`. */
export function unfairRow(mode: string, difficulty: string): UnfairRow | undefined {
  if (!Object.hasOwn(UNFAIR, mode)) return undefined;
  const rows = UNFAIR[mode];
  if (rows === undefined || !Object.hasOwn(rows, difficulty)) return undefined;
  return rows[difficulty];
}

/** Is any difficulty of this board flagged? The menu marks the row rather than
 * the difficulty, because the difficulty pills live at the bottom of the page
 * and the mark has to mean something before one is chosen. */
export function isUnfairMode(mode: string): boolean {
  return Object.hasOwn(UNFAIR, mode);
}

/** The one-line warning shown against a flagged row. Deliberately about the
 * cause rather than the number: "43% instead of 96%" reads as a bug report,
 * while "the tiling forces guesses" is the thing the player can act on by
 * picking another board. */
export function unfairHint(mode: string): string | undefined {
  if (!isUnfairMode(mode)) return undefined;
  return "Forced guesses — this tiling has look-alike cells no number can tell apart";
}

/** Pick from `pool` at random, dealing flagged boards a quarter as often.
 *
 * `random` is injectable so the unit tests can pin the weighting instead of
 * sampling it. */
export function pickWeighted(pool: string[], random: () => number = Math.random):
  string | undefined {
  if (pool.length === 0) return undefined;
  const weights = pool.map((mode) => (isUnfairMode(mode) ? UNFAIR_RANDOM_WEIGHT : 1));
  const total = weights.reduce((a, b) => a + b, 0);
  let ticket = random() * total;
  for (let i = 0; i < pool.length; i++) {
    ticket -= weights[i] ?? 1;
    if (ticket < 0) return pool[i];
  }
  return pool[pool.length - 1];
}
