"""Turn the calibration run into a reviewable table.

480 mine counts are not reviewable as a diff of integers. This writes
``report.md``: every board with its size, its mean degree, the density it
landed on and the win rate that density actually measured, so the numbers can
be argued with rather than trusted.

Run: ``PYTHONPATH=. python -m scripts.difficulty.report``
"""

from __future__ import annotations

import json
from pathlib import Path

from scripts.difficulty.calibrate import FINAL_GAMES, TOLERANCE

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
DIFFICULTIES = ("easy", "medium", "hard")


def load() -> list[dict]:
    path = HERE / "calibration.jsonl"
    return [
        json.loads(line) for line in path.read_text().splitlines() if line.strip()
    ]


def main() -> int:
    rows = load()
    targets = json.loads((HERE / "targets.json").read_text())
    by_mode: dict[str, dict[str, dict]] = {}
    for row in rows:
        by_mode.setdefault(row["mode"], {})[row["difficulty"]] = row

    out: list[str] = []
    out.append("# Difficulty calibration\n")
    out.append(
        "Every board's mine count, chosen so its win probability under the "
        "reference solver matches the classic board's. Generated by "
        "`scripts/difficulty/`; do not hand-edit.\n"
    )
    out.append("## The yardstick\n")
    out.append("| difficulty | classic board | win rate |")
    out.append("| --- | --- | --- |")
    sizes = {"easy": "9x9, 10 mines", "medium": "16x16, 40 mines",
             "hard": "30x16, 99 mines"}
    for difficulty in DIFFICULTIES:
        out.append(f"| {difficulty} | {sizes[difficulty]} | "
                   f"{targets[difficulty]:.1%} |")
    out.append("")

    uncalibrated = [r for r in rows if not r.get("calibrated")]
    out.append("## Coverage\n")
    out.append(
        f"- {len(rows)} rows, {len(rows) - len(uncalibrated)} on target "
        f"(within {TOLERANCE * 100:.0f} points of the classic win rate -- about "
        f"what {FINAL_GAMES} games per measurement can resolve, and far below "
        f"what a player would notice)"
    )
    if uncalibrated:
        out.append(f"- {len(uncalibrated)} could not be brought on target:")
        for row in sorted(uncalibrated, key=lambda r: r["mode"]):
            out.append(
                f"  - `{row['mode']}`/{row['difficulty']}: "
                f"{row['winRate']:.1%} vs {row['target']:.1%} "
                f"— {row.get('reason', 'unknown')}"
            )
    abandoned = [r for r in rows if r.get("abandoned")]
    if abandoned:
        out.append(f"- {len(abandoned)} rows had games the solver abandoned "
                   "(its frontier DP hit its node budget); their rates are "
                   "measured over the games that finished:")
        for row in sorted(abandoned, key=lambda r: -r["abandoned"])[:10]:
            out.append(f"  - `{row['mode']}`/{row['difficulty']}: "
                       f"{row['abandoned']} abandoned")
    out.append("")

    densities = sorted(r["density"] for r in rows)
    out.append(
        f"Densities run from {densities[0]:.1%} to {densities[-1]:.1%} "
        f"(median {densities[len(densities) // 2]:.1%}) — the spread the old "
        "flat 14/16/19 per cent could not express.\n"
    )

    floors = sorted(r["openingFloor"] / r["cells"] for r in rows
                    if "openingFloor" in r)
    if floors:
        out.append(
            "The only floor under the search is the **opening**: the fewest "
            "mines at which the first click alone stops finishing the board "
            f"(`calibrate.opening_floor`). As a density that runs "
            f"{floors[0]:.1%} to {floors[-1]:.1%} across the zoo — which is "
            "why it is measured per board rather than set as a percentage.\n"
        )

    out.append("## Every board\n")
    out.append("| mode | deg | easy | medium | hard |")
    out.append("| --- | --- | --- | --- | --- |")
    for mode in sorted(by_mode):
        entries = by_mode[mode]
        degree = next(iter(entries.values()))["meanDegree"]
        cells = []
        for difficulty in DIFFICULTIES:
            row = entries.get(difficulty)
            if row is None:
                cells.append("—")
                continue
            mark = "" if row.get("calibrated") else " ⚠"
            cells.append(
                f"{row['cells']}c {row['mines']}m "
                f"({row['density']:.0%}) {row['winRate']:.0%}{mark}"
            )
        out.append(f"| `{mode}` | {degree:.1f} | " + " | ".join(cells) + " |")
    out.append("")
    out.append(
        "`c` cells, `m` mines, then density and the measured win rate. "
        "⚠ marks a row the calibration could not bring on target.\n"
    )

    path = HERE / "report.md"
    path.write_text("\n".join(out))
    print(f"wrote {path} ({len(rows)} rows)")

    # And the machine-readable half, for the front-ends. A board flagged
    # `fair: false` is one whose tiling forces coin flips the player cannot
    # avoid; the app warns about those and deals them less often at random,
    # rather than letting them read as ordinary boards that the player is
    # simply losing.
    flags: dict[str, dict[str, dict]] = {}
    for row in rows:
        if row.get("fair", True):
            continue
        flags.setdefault(row["mode"], {})[row["difficulty"]] = {
            "winRate": row["winRate"],
            "target": row["target"],
            "reason": row.get("reason", ""),
        }
    payload = {
        "_comment": "Generated by scripts/difficulty/report.py. Boards whose "
        "tiling forces unavoidable coin flips, so their win rate cannot reach "
        "the difficulty's target. Both front-ends read this to warn the player "
        "and to deal these boards less often at random.",
        "unfair": dict(sorted(flags.items())),
    }
    data = ROOT / "data" / "difficulty.json"
    data.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {data} ({len(flags)} flagged modes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
