import { describe, expect, it } from "vitest";
import raw from "@data/difficulty.json";
import {
  WARNED_RANDOM_WEIGHT,
  blockedExplanation,
  blockedModes,
  fairnessHint,
  fairnessOf,
  modeFairness,
  pickWeighted,
  unfairRow,
} from "../../src/boards/fairness";
import { MODES, hasMode } from "../../src/boards/presets";

// `data/difficulty.json` is generated by `scripts/difficulty/` and grades the
// boards the calibration could not bring on target: `blocked` cannot be played
// at all, `warn` is playable but materially harder than its difficulty says.
// What is pinned here is how the app *uses* that grading -- the list itself
// moves whenever the calibration is re-run, and pinning its contents would only
// make a re-run look like a regression.

const UNFAIR = (raw as {
  unfair: Record<string, Record<string, { level: string; winRate: number }>>;
}).unfair;

describe("the graded-board list", () => {
  it("names only real modes and only known grades", () => {
    for (const [mode, rows] of Object.entries(UNFAIR)) {
      expect(hasMode(mode), mode).toBe(true);
      for (const row of Object.values(rows)) {
        expect(["warn", "blocked"]).toContain(row.level);
      }
    }
  });

  it("leaves the great majority of boards alone", () => {
    // The grade is an exception, not a category: if it ever covered a large
    // slice of the catalogue it would stop meaning anything on the rows that
    // carry it, and the calibration would be the thing to fix.
    expect(Object.keys(UNFAIR).length).toBeLessThan(MODES.length / 4);
  });

  it("only blocks boards that really cannot be won", () => {
    // The bar for taking a board out of play is that it is not a puzzle --
    // measured, not judged. Anything a player could actually finish belongs
    // behind a warning instead.
    for (const rows of Object.values(UNFAIR)) {
      for (const row of Object.values(rows)) {
        if (row.level === "blocked") expect(row.winRate).toBeLessThanOrEqual(0.1);
        else expect(row.winRate).toBeGreaterThan(0.1);
      }
    }
  });

  it("agrees with the lookups", () => {
    for (const [mode, rows] of Object.entries(UNFAIR)) {
      expect(modeFairness(mode)).not.toBe("ok");
      for (const [difficulty, row] of Object.entries(rows)) {
        expect(unfairRow(mode, difficulty)).toBeDefined();
        expect(fairnessOf(mode, difficulty)).toBe(row.level);
        expect(fairnessHint(row.level as "warn" | "blocked")).toBeTypeOf("string");
      }
    }
  });

  it("takes the worst grade for the mode as a whole", () => {
    // The menu marks the row, not the difficulty, so a board blocked at any
    // difficulty must read as blocked before one is chosen.
    for (const mode of blockedModes()) {
      expect(modeFairness(mode)).toBe("blocked");
      expect(Object.values(UNFAIR[mode]!).some((r) => r.level === "blocked")).toBe(true);
    }
  });

  it("does not answer for inherited properties", () => {
    // `in` would say yes to `toString` here, and the mode can come straight
    // from a share link -- the bug link.ts was bitten by.
    expect(modeFairness("toString")).toBe("ok");
    expect(fairnessOf("constructor", "easy")).toBe("ok");
    expect(unfairRow("constructor", "easy")).toBeUndefined();
    const flagged = Object.keys(UNFAIR)[0];
    if (flagged) expect(unfairRow(flagged, "toString")).toBeUndefined();
  });

  it("leaves an ordinary board unmarked", () => {
    expect(modeFairness("square")).toBe("ok");
    expect(fairnessOf("square", "easy")).toBe("ok");
    expect(fairnessHint("ok")).toBeUndefined();
  });

  it("explains a blocked board in terms of the tiling", () => {
    const mode = blockedModes()[0];
    expect(mode).toBeDefined();
    const text = blockedExplanation(mode!, "easy");
    expect(text).toMatch(/look-alike/);
    expect(text.length).toBeGreaterThan(80);
  });
});

describe("weighted random picking", () => {
  const warned = Object.entries(UNFAIR).find(([, rows]) =>
    Object.values(rows).every((r) => r.level === "warn"),
  )?.[0];
  const blocked = blockedModes()[0];

  it("returns undefined for an empty pool", () => {
    expect(pickWeighted([])).toBeUndefined();
  });

  it("never deals a blocked board", () => {
    expect(blocked).toBeDefined();
    for (const r of [0, 0.25, 0.5, 0.75, 0.999]) {
      expect(pickWeighted(["square", blocked!], () => r)).toBe("square");
    }
    // ...and a pool of nothing but blocked boards deals nothing at all,
    // rather than falling back to one of them.
    expect(pickWeighted([blocked!], () => 0.5)).toBeUndefined();
  });

  it("still reaches a warned board", () => {
    expect(warned).toBeDefined();
    expect(pickWeighted([warned!], () => 0)).toBe(warned);
    expect(pickWeighted(["square", warned!], () => 0.999)).toBe(warned);
  });

  it("gives a warned board a quarter of an ordinary board's share", () => {
    const pool = ["square", warned!];
    // total weight 1 + 0.25; "square" holds the first 1/1.25 = 0.8 of it
    expect(pickWeighted(pool, () => 0.79)).toBe("square");
    expect(pickWeighted(pool, () => 0.81)).toBe(warned);
    expect(WARNED_RANDOM_WEIGHT).toBeLessThan(1);
  });

  it("is uniform when nothing in the pool is graded", () => {
    const pool = ["square", "hex", "triangle"];
    expect(pickWeighted(pool, () => 0.0)).toBe("square");
    expect(pickWeighted(pool, () => 0.5)).toBe("hex");
    expect(pickWeighted(pool, () => 0.9)).toBe("triangle");
  });
});
