import { describe, expect, it } from "vitest";
import raw from "@data/difficulty.json";
import {
  UNFAIR_RANDOM_WEIGHT,
  isUnfairMode,
  pickWeighted,
  unfairHint,
  unfairRow,
} from "../../src/boards/fairness";
import { MODES, hasMode } from "../../src/boards/presets";

// `data/difficulty.json` is generated by `scripts/difficulty/` and lists the
// boards whose tiling forces coin flips, so their win rate cannot reach the
// difficulty's target however the mine count is chosen. What is pinned here is
// how the app *uses* that list -- the list itself moves whenever the
// calibration is re-run, and pinning its contents would only make a re-run
// look like a regression.

const UNFAIR = (raw as { unfair: Record<string, Record<string, unknown>> }).unfair;

describe("the unfair-board list", () => {
  it("names only real modes", () => {
    for (const mode of Object.keys(UNFAIR)) {
      expect(hasMode(mode), mode).toBe(true);
    }
  });

  it("leaves the great majority of boards alone", () => {
    // The flag is a warning, not a category: if it ever covered a large slice
    // of the catalogue it would stop meaning anything on the rows that carry
    // it, and the calibration would be the thing to fix.
    expect(Object.keys(UNFAIR).length).toBeLessThan(MODES.length / 3);
  });

  it("agrees with the row lookup", () => {
    for (const [mode, rows] of Object.entries(UNFAIR)) {
      expect(isUnfairMode(mode)).toBe(true);
      expect(unfairHint(mode)).toBeTypeOf("string");
      for (const difficulty of Object.keys(rows)) {
        expect(unfairRow(mode, difficulty)).toBeDefined();
      }
    }
  });

  it("does not answer for inherited properties", () => {
    // `in` would say yes to `toString` here, and the mode can come straight
    // from a share link -- the bug link.ts was bitten by.
    expect(isUnfairMode("toString")).toBe(false);
    expect(unfairRow("constructor", "easy")).toBeUndefined();
    const flagged = Object.keys(UNFAIR)[0];
    if (flagged) expect(unfairRow(flagged, "toString")).toBeUndefined();
  });

  it("never flags the classic board", () => {
    expect(isUnfairMode("square")).toBe(false);
    expect(unfairHint("square")).toBeUndefined();
  });
});

describe("weighted random picking", () => {
  const flagged = Object.keys(UNFAIR)[0] ?? "triakis";

  it("returns undefined for an empty pool", () => {
    expect(pickWeighted([])).toBeUndefined();
  });

  it("still reaches a flagged board", () => {
    // Deranked, not hidden: the very top of the ticket range is the last
    // entry, whichever it is.
    expect(pickWeighted([flagged], () => 0)).toBe(flagged);
    expect(pickWeighted(["square", flagged], () => 0.999)).toBe(flagged);
  });

  it("gives a flagged board a quarter of an ordinary board's share", () => {
    const pool = ["square", flagged];
    // total weight 1 + 0.25; "square" holds the first 1/1.25 = 0.8 of it
    expect(pickWeighted(pool, () => 0.79)).toBe("square");
    expect(pickWeighted(pool, () => 0.81)).toBe(flagged);
    expect(UNFAIR_RANDOM_WEIGHT).toBeLessThan(1);
  });

  it("is uniform when nothing in the pool is flagged", () => {
    const pool = ["square", "hex", "triangle"];
    expect(pickWeighted(pool, () => 0.0)).toBe("square");
    expect(pickWeighted(pool, () => 0.5)).toBe("hex");
    expect(pickWeighted(pool, () => 0.9)).toBe("triangle");
  });
});
