"""Dump the straightening rules and the wrapped geometry they produce.

The conformance oracle in ``data/conformance.json`` counts cells, edges and
vertices, which straightening does not change -- it moves points without
merging any -- so nothing there would notice the TypeScript port drifting from
this one. This writes the positions themselves, for the tilings that have a
rule and one board per surface, into the fixture
``web/tests/unit/straighten.fixture.json``.

Run: ``PYTHONPATH=. python scripts/export_straighten_fixture.py``
"""

from __future__ import annotations

import json
from pathlib import Path

from minesweeper.boards.presets import build_board
from minesweeper.boards.tilings import ARCH_TILINGS, _arch_template

OUT = (Path(__file__).resolve().parent.parent / "web" / "tests" / "unit"
       / "straighten.fixture.json")
# one board per surface, on the tiling the rule was written for
BOARDS = ["torusbasketweave3", "cylbasketweave3", "mobiusbasketweave3",
          "kleinbasketweave3", "kleinbasketweave"]


def main() -> int:
    rules = {}
    for tiling in ARCH_TILINGS:
        template = _arch_template(tiling.key)
        if not template.straight:
            continue
        # tags are emitted as the two numbers they are made of; the test
        # rebuilds the TypeScript tag string from them, so neither side has to
        # match the other's float formatting
        rows = []
        for tag, (t, a, b) in sorted(template.straight.items()):
            rows.append([tag[0], tag[1], t,
                         a[0][0], a[0][1], a[1], a[2],
                         b[0][0], b[0][1], b[1], b[2]])
        rules[tiling.key] = rows

    boards = {}
    for mode in BOARDS:
        board = build_board(mode, "easy")
        # each polygon flattened to its coordinates, the list sorted so the
        # two implementations need not agree on cell order
        boards[mode] = sorted(
            [round(c, 6) for point in polygon for c in point]
            for polygon in board.polygons.values()
        )

    OUT.write_text(json.dumps({
        "_comment": "Generated by scripts/export_straighten_fixture.py -- the "
                    "straightening rules and the geometry they produce, which "
                    "the combinatorial conformance oracle cannot see.",
        "tilings": [tiling.key for tiling in ARCH_TILINGS],
        "rules": rules,
        "boards": boards,
    }, indent=1) + "\n")
    print(f"wrote {OUT} ({len(rules)} tilings, {len(boards)} boards)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
