"""Export the board conformance oracle (data/conformance.json).

For every ported mode × difficulty, record the board statistics the Python
implementation produces — cell count, mine count, Euler characteristic,
boundary components, edge count, whether the board carries a cell cycle. The
TypeScript vitest suite asserts its own boards reproduce these exactly, so the
two implementations cannot drift. Committed; a CI job regenerates and diffs it.

The ported set grows per milestone: it is exactly the modes present in
data/presets.json (the ones both front-ends build).

The aperiodic substitution boards (Penrose, the Spectre) are one preset each
but a whole family of boards: the game seed picks which of the measured windows
onto the grown patch the board is (``presets.window_for``, then
``aperiodic._window``), and a window that lands on a different tile in one
language is a silently different board. So those modes are exported a second
time, at a few fixed seeds, under ``seeds`` -- which pins the whole path a deal
takes, the shared window list included.

Usage: PYTHONPATH=. python scripts/export_conformance.py
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from minesweeper.boards._data import load
from minesweeper.boards.core import (
    DIFFICULTIES,
    boundary_components,
    corner_fans,
    euler_characteristic,
)
from minesweeper.boards.presets import _VARIANT_BUILDERS, build_board

DATA = Path(__file__).resolve().parent.parent / "data"


def _edge_count(board) -> int:
    edges = set()
    for polygon in board.polygons.values():
        pts = [tuple(round(c, 6) for c in p) for p in polygon]
        for a, b in zip(pts, pts[1:] + pts[:1]):
            edges.add(frozenset((a, b)))
    return len(edges)


def _stats(board) -> dict:
    return {
        "cellCount": len(board.polygons),
        "mineCount": board.mine_count,
        "euler": euler_characteristic(board),
        "boundaryComponents": boundary_components(board),
        "edgeCount": _edge_count(board),
        "vertexCount": len(corner_fans(board)),
        "hasCellCycle": getattr(board, "cell_cycle", None) is not None,
    }


#: The game seeds pinned for every aperiodic mode. 0 and 1 are the first two
#: windows of the measured list; 3407 is a seed that wraps deep into it, where
#: an index or a stride that disagreed by one would have wandered off on its
#: own.
SEEDS = [0, 1, 2, 3407]


def main() -> int:
    presets = load("presets")["presets"]
    ported = list(presets)
    out: dict[str, dict[str, dict]] = defaultdict(dict)
    for mode in ported:
        for difficulty in DIFFICULTIES:
            out[mode][difficulty] = _stats(build_board(mode, difficulty))

    varying = [m for m in ported if presets[m]["builder"] in _VARIANT_BUILDERS]
    seeds: dict[str, dict[str, dict]] = defaultdict(dict)
    for mode in varying:
        for difficulty in DIFFICULTIES:
            seeds[mode][difficulty] = {
                str(seed): _stats(build_board(mode, difficulty, seed))
                for seed in SEEDS
            }

    payload = {
        "_comment": "Generated by scripts/export_conformance.py. Board "
        "statistics per ported mode × difficulty; the TypeScript conformance "
        "tests assert against these so the two implementations cannot drift. "
        "`seeds` repeats the aperiodic modes at fixed game seeds, where one "
        "preset is a family of boards rather than a single one and the seed "
        "picks which measured window onto the patch is dealt.",
        "modes": dict(out),
        "seeds": dict(seeds),
    }
    path = DATA / "conformance.json"
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {path} ({len(ported)} modes, {len(varying)} of them varying)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
